Fix [UI] add data-testid for elements in batch run wizard
iguazio/dashboard-react-controls pull request #216
Opened 2023-11-29 15:17 UTC by ilan7empest

- **UI**: Add data-testid for elements in batch run wizard
   Jira: [ML-4925](https://jira.iguazeng.com/browse/ML-4925)

2023-11-29 16:42 UTC, mavdryk requested changes

2023-11-29 16:42 UTC, mavdryk commented on src/lib/elements/FormActionButton/FormActionButton.js
> +  id: PropTypes.string,
There should be a default value for not required props

2023-11-29 16:42 UTC, mavdryk commented on src/lib/elements/FormRowActions/FormRowActions.js
> +            id={editingItem.ui?.isNew ? 'delete-btn' : 'discard-btn'}
No need to have different IDs

2023-11-29 17:44 UTC, ilan7empest commented on src/lib/elements/FormRowActions/FormRowActions.js
> +            id={editingItem.ui?.isNew ? 'delete-btn' : 'discard-btn'}
It's for QA purpose, do be able to  differentiate between the actions.

2023-12-01 10:19 UTC, mavdryk requested changes

2023-12-01 10:19 UTC, mavdryk commented on src/lib/components/FormCheckBox/FormCheckBox.js
> +              data-testid={inputProps.value ?? name ? `${name}-form-checkbox` : 'form-checkbox'}
inputProps.value is redundant here. It's not used for the id

2023-12-01 10:19 UTC, mavdryk commented on src/lib/components/FormRadio/FormRadio.js
> +            data-testid={name ? `${name}-form-radio` : 'form-radio'}
Probably for the FormRadio component we also need to add `value` to the `id`. Because in radio buttons the name isn't unique. name + value is unique

2023-12-04 08:50 UTC, merged